[package]
name = "attic"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-stream = { version = "0.3.5", optional = true }
base64 = "0.22.1"
bytes = "1.4.0"
displaydoc = "0.2.4"
digest = "0.10.7"
ed25519-compact = "2.0.4"
fastcdc = "3.0.3"
futures = "0.3.28"
hex = "0.4.3"
lazy_static = "1.4.0"
log = "0.4.18"
nix-base32 = { git = "https://github.com/zhaofengli/nix-base32.git", rev = "b850c6e9273d1c39bd93abb704a53345f5be92eb" }
regex = "1.8.3"
serde = { version = "1.0.163", features = ["derive"] }
serde_yaml = "0.9.21"
serde_with = "3.0.0"
sha2 = "0.10.6"
tempfile = "3"
wildmatch = "2.1.1"
xdg = "2.5.0"

# Native libnixstore bindings.
cxx = { version = "1.0", optional = true }

[dependencies.tokio]
version = "1.28.2"
optional = true
features = [
	"fs",
	"io-util",
	"macros",
	"process",
	"sync",
]

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports", "async_tokio"] }
fastcdc = { version = "*", features = ["tokio"] }
serde_json = "1.0.96"

[build-dependencies]
cc = "1.1.13"
cxx-build = { version = "1.0", optional = true }
pkg-config = "0.3.27"
tempfile = "3"
version-compare = "0.2.0"

[features]
default = [
	"chunking",
	"nix_store",
	"stream",
	"tokio",
]

# Chunking.
chunking = ["tokio", "dep:async-stream"]

# Native libnixstore bindings.
#
# When disabled, the native Rust portions of nix_store can still be used.
nix_store = ["tokio", "dep:cxx", "dep:cxx-build"]

# Stream utilities.
stream = ["tokio", "dep:async-stream"]

# Tokio runtime.
tokio = ["dep:tokio", "tokio/rt"]

[[bench]]
name = "chunking"
harness = false
